version: '3'

services:
  gonative-ticketing:
    image: danimgomes/gonative-ticketing:v1.3
    volumes:
        - /home/dm746/tickets.db:/usr/app/instance/tickets.db
    ports:
      - "80:8000"
    env_file: .env